workflows:
  unity-android-workflow:
    name: Unity Android Build
    triggering:
      events: []
    
    environment:
      unity: "2022.3.62f3"
      groups:
        - unity_credentials
      vars:
        PROJECT_NAME: "ChikenLine"  # Без пробелов!
        BUNDLE_ID: "com.line.egg"
        VERSION_NAME: "1.0.0"
        VERSION_CODE: "1"
        UNITY_VERSION: "2022.3.62f3"  # ДОБАВЬ ЭТУ СТРОЧКУ!
    
    scripts:
      # 1. АКТИВАЦИЯ ЛИЦЕНЗИИ (ИСПРАВЛЕННАЯ)
      - name: Activate Unity License
        script: |
          echo "📱 Активация лицензии Unity..."
          echo "Serial: ${UNITY_SERIAL:0:10}..."
          
          # Возвращаем текущую лицензию
          echo "Возвращаем текущую лицензию..."
          /Users/Shared/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode -nographics -quit -returnlicense \
            -logFile /tmp/return.log 2>&1 || true
          
          sleep 3
          
          # Активируем новую лицензию
          echo "Активируем лицензию..."
          /Users/Shared/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -quit \
            -serial "$UNITY_SERIAL" \
            -username "$UNITY_USERNAME" \
            -password "$UNITY_PASSWORD" \
            -logFile /tmp/activate.log \
            2>&1
          
          ACTIVATION_RESULT=$?
          echo "Код выхода: $ACTIVATION_RESULT"
          
          if [ $ACTIVATION_RESULT -eq 0 ]; then
            echo "✅ Лицензия активирована!"
            echo "Последние строки лога:"
            tail -10 /tmp/activate.log
          else
            echo "❌ Ошибка активации! Лог:"
            cat /tmp/activate.log
            exit 1
          fi
      
      # 2. Сборка AAB
      - name: Build Android App Bundle
        script: |
          echo "📦 Сборка AAB..."
          
          /Users/Shared/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.aab" \
            -buildTarget "Android" \
            -androidAppBundle "true" \
            -logFile "$CM_BUILD_DIR/build.log"
          
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.aab" ]; then
            echo "✅ AAB готов!"
            ls -la "$CM_BUILD_DIR/$PROJECT_NAME.aab"
          else
            echo "❌ Ошибка сборки AAB"
            cat "$CM_BUILD_DIR/build.log"
            exit 1
          fi
      
      # 3. Сборка APK
      - name: Build APK
        script: |
          echo "📱 Сборка APK..."
          
          /Users/Shared/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.apk" \
            -buildTarget "Android" \
            -androidAppBundle "false" \
            -logFile "$CM_BUILD_DIR/build_apk.log"
          
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.apk" ]; then
            echo "✅ APK готов!"
            ls -la "$CM_BUILD_DIR/$PROJECT_NAME.apk"
          else
            echo "❌ Ошибка сборки APK"
            cat "$CM_BUILD_DIR/build_apk.log"
            exit 1
          fi
    
    artifacts:
      - "$CM_BUILD_DIR/*.aab"
      - "$CM_BUILD_DIR/*.apk"
      - "$CM_BUILD_DIR/*.log"
    
   
