workflows:
  unity-android-workflow:
    name: Unity Android Build
    triggering:
      events: []  # Только ручной запуск
    
    environment:
      os: macos  # Собираем на Mac (там больше версий)
      
      # Группы с секретными данными (настраиваются в интерфейсе CodeMagic)
      groups:
        - unity_credentials  # Должна содержать: UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD
        - android_signing    # Для подписи APK (пока можно не настраивать)
      
      # Твои переменные (подставятся в скрипты)
      vars:
        PROJECT_NAME: "ChikenLine"     # Без пробелов!
        BUNDLE_ID: "com.line.egg"
        VERSION_NAME: "1.0.0"
        VERSION_CODE: "1"
        # UNITY_VERSION будет взят из окружения CodeMagic
    
    # САМАЯ ВАЖНАЯ ЧАСТЬ - СКРИПТЫ
    scripts:
      # 1. АКТИВАЦИЯ ЛИЦЕНЗИИ (РАБОЧИЙ ВАРИАНТ)
      - name: Activate Unity License
        script: |
          echo "=== АКТИВАЦИЯ ЛИЦЕНЗИИ UNITY ==="
          
          # Путь к установленной Unity на Mac в CodeMagic
          UNITY_PATH="/Applications/Unity/Hub/Editor/$(cat /Users/builder/unity_version)/Unity.app/Contents/MacOS/Unity"
          echo "Путь к Unity: $UNITY_PATH"
          
          # 1. Возвращаем старую лицензию (если есть)
          echo "Шаг 1: Возвращаем лицензию..."
          $UNITY_PATH -batchmode -nographics -quit -returnlicense -logFile /tmp/unity_return.log 2>&1 || true
          echo "Готово"
          
          sleep 2
          
          # 2. Активируем новую лицензию
          echo "Шаг 2: Активируем с серийным номером..."
          $UNITY_PATH \
            -batchmode \
            -nographics \
            -quit \
            -serial "$UNITY_SERIAL" \
            -username "$UNITY_USERNAME" \
            -password "$UNITY_PASSWORD" \
            -logFile /tmp/unity_activate.log \
            2>&1
          
          # 3. Проверяем результат
          ACTIVATION_RESULT=$?
          echo "Код выхода Unity: $ACTIVATION_RESULT"
          
          if [ $ACTIVATION_RESULT -eq 0 ]; then
            echo "✅ ЛИЦЕНЗИЯ АКТИВИРОВАНА УСПЕШНО!"
            echo "Последние строки лога:"
            tail -5 /tmp/unity_activate.log
          else
            echo "❌ ОШИБКА АКТИВАЦИИ ЛИЦЕНЗИИ!"
            echo "=== ПОЛНЫЙ ЛОГ ОШИБКИ ==="
            cat /tmp/unity_activate.log
            echo "=== КОНЕЦ ЛОГА ==="
            
            # Подсказки по частым ошибкам
            if grep -i "invalid" /tmp/unity_activate.log; then
              echo "ВОЗМОЖНАЯ ПРИЧИНА: Неверный серийный номер, логин или пароль"
            elif grep -i "already in use" /tmp/unity_activate.log; then
              echo "ВОЗМОЖНАЯ ПРИЧИНА: Лицензия уже используется на другом компьютере"
            fi
            
            exit 1
          fi
      
      # 2. СБОРКА AAB (ДЛЯ GOOGLE PLAY)
      - name: Build Android App Bundle (AAB)
        script: |
          echo "=== СБОРКА AAB ФАЙЛА ==="
          
          UNITY_PATH="/Applications/Unity/Hub/Editor/$(cat /Users/builder/unity_version)/Unity.app/Contents/MacOS/Unity"
          
          $UNITY_PATH \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.aab" \
            -buildTarget "Android" \
            -androidAppBundle "true" \
            -logFile "$CM_BUILD_DIR/build_aab.log" \
            2>&1
          
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.aab" ]; then
            echo "✅ AAB УСПЕШНО СОБРАН!"
            echo "Размер: $(du -h "$CM_BUILD_DIR/$PROJECT_NAME.aab" | cut -f1)"
            echo "Путь: $CM_BUILD_DIR/$PROJECT_NAME.aab"
          else
            echo "❌ ОШИБКА ПРИ СБОРКЕ AAB"
            echo "Лог ошибок:"
            cat "$CM_BUILD_DIR/build_aab.log"
            exit 1
          fi
      
      # 3. СБОРКА APK (ДЛЯ ТЕСТИРОВАНИЯ)
      - name: Build APK for Testing
        script: |
          echo "=== СБОРКА APK ФАЙЛА ==="
          
          UNITY_PATH="/Applications/Unity/Hub/Editor/$(cat /Users/builder/unity_version)/Unity.app/Contents/MacOS/Unity"
          
          $UNITY_PATH \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.apk" \
            -buildTarget "Android" \
            -androidAppBundle "false" \
            -logFile "$CM_BUILD_DIR/build_apk.log" \
            2>&1
          
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.apk" ]; then
            echo "✅ APK УСПЕШНО СОБРАН!"
            echo "Размер: $(du -h "$CM_BUILD_DIR/$PROJECT_NAME.apk" | cut -f1)"
            echo "Путь: $CM_BUILD_DIR/$PROJECT_NAME.apk"
          else
            echo "❌ ОШИБКА ПРИ СБОРКЕ APK"
            echo "Лог ошибок:"
            cat "$CM_BUILD_DIR/build_apk.log"
            exit 1
          fi
    
    # ЧТО СОХРАНИТЬ ПОСЛЕ СБОРКИ
    artifacts:
      - "$CM_BUILD_DIR/*.aab"
      - "$CM_BUILD_DIR/*.apk"
      - "$CM_BUILD_DIR/*.log"
      - "/tmp/unity_*.log"
    
    
