# Codemagic YAML для Unity Android сборки
# Обновлено под новую версию CodeMagic
# Документация: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  unity-android-workflow:
    name: Unity Android Build
    
    # Триггеры сборки - только ручной запуск
    triggering:
      events: []  # Пустой массив = только ручной запуск
    
    # Среда выполнения
    environment:
      # Укажите свою версию Unity
      unity: "2022.3.62f3"  # ПРОСТО СТРОКА, не объект!
      
      # Группы переменных (настроим в интерфейсе CodeMagic)
      groups:
        - unity_credentials
        - android_signing
      
      # Переменные проекта
      vars:
        PROJECT_NAME: "Chiken Line"
        BUNDLE_ID: "com.line.egg"
        VERSION_NAME: "1.0.0"
        VERSION_CODE: "1"
    
    # Скрипты сборки
    scripts:
      # 1. Активация лицензии Unity
      - name: Activate Unity License
        script: |
          echo "📱 Активация лицензии Unity..."
          
          # Сначала попробуем вернуть лицензию, если она есть
          unity-editor -batchmode -nographics -quit -returnlicense -logFile /tmp/unity_return.log 2>/dev/null || true
          
          # Активируем лицензию
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -logFile /tmp/unity_activate.log \
            -serial "$UNITY_SERIAL" \
            -username "$UNITY_USERNAME" \
            -password "$UNITY_PASSWORD" \
            > /tmp/unity_output.log 2>&1
          
          # Проверяем успешность активации
          if [ $? -eq 0 ]; then
            echo "✅ Лицензия Unity активирована успешно"
          else
            echo "❌ Ошибка активации лицензии Unity"
            cat /tmp/unity_activate.log
            exit 1
          fi
      
      # 2. Сборка AAB (App Bundle)
      - name: Build Android App Bundle (AAB)
        script: |
          echo "📦 Сборка AAB файла..."
          
          # Создаем папку для сборки
          mkdir -p "$CM_BUILD_DIR"
          
          # Запускаем сборку через Unity
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.aab" \
            -buildTarget "Android" \
            -androidAppBundle "true" \
            -development "false" \
            -logFile "$CM_BUILD_DIR/build_aab.log"
          
          # Проверяем результат
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.aab" ]; then
            echo "✅ AAB собран успешно!"
            echo "Размер файла: $(du -h "$CM_BUILD_DIR/$PROJECT_NAME.aab" | cut -f1)"
          else
            echo "❌ Ошибка сборки AAB"
            cat "$CM_BUILD_DIR/build_aab.log"
            exit 1
          fi
      
      # 3. Сборка APK (для тестирования)
      - name: Build APK (ARM64)
        script: |
          echo "📱 Сборка APK файла..."
          
          # Запускаем сборку APK
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -executeMethod BuildCommand.PerformBuild \
            -outputPath "$CM_BUILD_DIR/$PROJECT_NAME.apk" \
            -buildTarget "Android" \
            -androidAppBundle "false" \
            -development "false" \
            -logFile "$CM_BUILD_DIR/build_apk.log"
          
          # Проверяем результат
          if [ -f "$CM_BUILD_DIR/$PROJECT_NAME.apk" ]; then
            echo "✅ APK собран успешно!"
            echo "Размер файла: $(du -h "$CM_BUILD_DIR/$PROJECT_NAME.apk" | cut -f1)"
          else
            echo "❌ Ошибка сборки APK"
            cat "$CM_BUILD_DIR/build_apk.log"
            exit 1
          fi
    
    # Артефакты (сохраняемые файлы)
    artifacts:
      - "build/**/*.aab"
      - "build/**/*.apk"
      - "build/**/*.log"
      - "$CM_BUILD_DIR/*.aab"
      - "$CM_BUILD_DIR/*.apk"
      - "$CM_BUILD_DIR/*.log"
    
   
